apiVersion: opensearch.opni.io/v1beta1
kind: OpensearchCluster
metadata:
  name: ot-os
  namespace: default
spec:
  version: 1.1.0
  master:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
  data:
    replicas: 3
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 2Gi